name: ai
channels:
  - anaconda
  - conda-forge
dependencies:
  - pip
  - pip:
      - ipykernel
      - matplotlib
      - pandas
      - scikit-learn
      - scipy
      - torch
      - torchinfo
      - tqdm
